#mongodb+srv://narru:<password>@recipes.8zxgu2j.mongodb.net/test
spring:
 data:
  mongodb: #(down) mongodb atlas database user connection uri
   uri : mongodb+srv://narru:narru@recipes.8zxgu2j.mongodb.net/test
   database : Recipes #mongodb database